### ISSUE TITLE
iFrame loads only on remote firefox, not locally on pi/MM

### ISSUE THREAD

**Issue by flo269** [AgP42/MMM-SmartWebDisplay#1]
Hi,

I'm running the latest master of MM on a raspi.
I installed MMM-SmartWebDisplay and when I connect to http://magicmirror:8080 from Firefox on my mac, the iFrame gets displayed as expected. However, it does not get displayed "locally" on the raspi/MM itsself.

Any hint on what I could be doing wrong? :-)

Thanks a lot!
Cheers
Flo

config: {
				logDebug: true,
				height: "104px",
				width: "294px",
				updateInterval: 1, 
				NextURLInterval: 0,
				displayStateInfos: false,
				displayLastUpdate: false,
				displayLastUpdateFormat: 'ddd - HH:mm:ss',
				url: ["http://user:pass@10.10.10.58/lcd.htm"],
				scrolling: "no"
				}

**Comment by AgP42** [comment]
Hello,

I guess it comes from the fact that you need to login with user/password, I also faced such problems previously. 

I will check more and let you know !

Bye,
AgP

**Comment by AgP42** [comment]
Hello @flo269 , 

as I cannot test your URL directly (because I don't know it ! ;-) ), could you please do the following steps : 
- if you can remove the user/pass authentication, please remove it and test again on the MagicMirror => to ensure the issue comes from it...
- On the computer (Firefox on mac), does this browser have a cookies or any previous successful authentication that he was able to store ? To check it can you empty all your cookies, test the URL (without user/pass) to ensure it is NOT displayed, and then test again with RemoteControl

No other ideas for now...

Let me know, 
AgP

**Comment by jasestu** [comment]
I think I'm having a similar issue. 
I'm using MM inside a network and the MM software won't display the pages, but if I run chromium on the same device and point it at itself as the server then it works fine.

**Comment by AgP42** [comment]
Hello, 

sorry for the very late answer. 

Yes it might be something like that. To test if the website you want to display on the module accept to be embedded into iFrames, you can use this tool : [https://jsfiddle.net/westonruter/6mSuK/](https://jsfiddle.net/westonruter/6mSuK/)

**Comment by AgP42** [comment]
Hi,

more than a month without answer, I consider it close, let me know if you still need help !

AgP
